name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
     

    steps:
    - uses: actions/checkout@v3
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: antlr4 libantlr4-runtime-dev default-jdk
    - name: make
      working-directory: ./compiler
      run: make
    - name: make check
      working-directory: ./compiler
      run: make check
